/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.woojean.rpc.demo;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-05-18")
public class Param implements org.apache.thrift.TBase<Param, Param._Fields>, java.io.Serializable, Cloneable, Comparable<Param> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Param");

  private static final org.apache.thrift.protocol.TField S1_FIELD_DESC = new org.apache.thrift.protocol.TField("s1", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField S2_FIELD_DESC = new org.apache.thrift.protocol.TField("s2", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ParamStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ParamTupleSchemeFactory();

  public java.lang.String s1; // required
  public java.lang.String s2; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    S1((short)1, "s1"),
    S2((short)2, "s2");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // S1
          return S1;
        case 2: // S2
          return S2;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.S1, new org.apache.thrift.meta_data.FieldMetaData("s1", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.S2, new org.apache.thrift.meta_data.FieldMetaData("s2", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Param.class, metaDataMap);
  }

  public Param() {
  }

  public Param(
    java.lang.String s1,
    java.lang.String s2)
  {
    this();
    this.s1 = s1;
    this.s2 = s2;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Param(Param other) {
    if (other.isSetS1()) {
      this.s1 = other.s1;
    }
    if (other.isSetS2()) {
      this.s2 = other.s2;
    }
  }

  public Param deepCopy() {
    return new Param(this);
  }

  @Override
  public void clear() {
    this.s1 = null;
    this.s2 = null;
  }

  public java.lang.String getS1() {
    return this.s1;
  }

  public Param setS1(java.lang.String s1) {
    this.s1 = s1;
    return this;
  }

  public void unsetS1() {
    this.s1 = null;
  }

  /** Returns true if field s1 is set (has been assigned a value) and false otherwise */
  public boolean isSetS1() {
    return this.s1 != null;
  }

  public void setS1IsSet(boolean value) {
    if (!value) {
      this.s1 = null;
    }
  }

  public java.lang.String getS2() {
    return this.s2;
  }

  public Param setS2(java.lang.String s2) {
    this.s2 = s2;
    return this;
  }

  public void unsetS2() {
    this.s2 = null;
  }

  /** Returns true if field s2 is set (has been assigned a value) and false otherwise */
  public boolean isSetS2() {
    return this.s2 != null;
  }

  public void setS2IsSet(boolean value) {
    if (!value) {
      this.s2 = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case S1:
      if (value == null) {
        unsetS1();
      } else {
        setS1((java.lang.String)value);
      }
      break;

    case S2:
      if (value == null) {
        unsetS2();
      } else {
        setS2((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case S1:
      return getS1();

    case S2:
      return getS2();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case S1:
      return isSetS1();
    case S2:
      return isSetS2();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Param)
      return this.equals((Param)that);
    return false;
  }

  public boolean equals(Param that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_s1 = true && this.isSetS1();
    boolean that_present_s1 = true && that.isSetS1();
    if (this_present_s1 || that_present_s1) {
      if (!(this_present_s1 && that_present_s1))
        return false;
      if (!this.s1.equals(that.s1))
        return false;
    }

    boolean this_present_s2 = true && this.isSetS2();
    boolean that_present_s2 = true && that.isSetS2();
    if (this_present_s2 || that_present_s2) {
      if (!(this_present_s2 && that_present_s2))
        return false;
      if (!this.s2.equals(that.s2))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetS1()) ? 131071 : 524287);
    if (isSetS1())
      hashCode = hashCode * 8191 + s1.hashCode();

    hashCode = hashCode * 8191 + ((isSetS2()) ? 131071 : 524287);
    if (isSetS2())
      hashCode = hashCode * 8191 + s2.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Param other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetS1()).compareTo(other.isSetS1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetS1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.s1, other.s1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetS2()).compareTo(other.isSetS2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetS2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.s2, other.s2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Param(");
    boolean first = true;

    sb.append("s1:");
    if (this.s1 == null) {
      sb.append("null");
    } else {
      sb.append(this.s1);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("s2:");
    if (this.s2 == null) {
      sb.append("null");
    } else {
      sb.append(this.s2);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (s1 == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 's1' was not present! Struct: " + toString());
    }
    if (s2 == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 's2' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ParamStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ParamStandardScheme getScheme() {
      return new ParamStandardScheme();
    }
  }

  private static class ParamStandardScheme extends org.apache.thrift.scheme.StandardScheme<Param> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Param struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // S1
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.s1 = iprot.readString();
              struct.setS1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // S2
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.s2 = iprot.readString();
              struct.setS2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Param struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.s1 != null) {
        oprot.writeFieldBegin(S1_FIELD_DESC);
        oprot.writeString(struct.s1);
        oprot.writeFieldEnd();
      }
      if (struct.s2 != null) {
        oprot.writeFieldBegin(S2_FIELD_DESC);
        oprot.writeString(struct.s2);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ParamTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ParamTupleScheme getScheme() {
      return new ParamTupleScheme();
    }
  }

  private static class ParamTupleScheme extends org.apache.thrift.scheme.TupleScheme<Param> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Param struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.s1);
      oprot.writeString(struct.s2);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Param struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.s1 = iprot.readString();
      struct.setS1IsSet(true);
      struct.s2 = iprot.readString();
      struct.setS2IsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

